export const ACHIEVEMENTS = [
  { id: 'first_habit', title: 'First Steps', description: 'Complete your first habit', icon: '🌱', xp: 50, check: (s) => s.habitsCompleted >= 1 },
  { id: 'habits_10', title: 'Habit Builder', description: 'Complete 10 habits total', icon: '💪', xp: 75, check: (s) => s.habitsCompleted >= 10 },
  { id: 'habits_50', title: 'Dedicated', description: 'Complete 50 habits total', icon: '🔥', xp: 150, check: (s) => s.habitsCompleted >= 50 },
  { id: 'habits_100', title: 'Habit Master', description: 'Complete 100 habits total', icon: '🏆', xp: 300, check: (s) => s.habitsCompleted >= 100 },
  { id: 'streak_3', title: 'On a Roll', description: 'Maintain a 3-day streak', icon: '⚡', xp: 30, check: (s) => s.streak >= 3 },
  { id: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🗓️', xp: 100, check: (s) => s.streak >= 7 },
  { id: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '🌙', xp: 500, check: (s) => s.streak >= 30 },
  { id: 'first_goal', title: 'Goal Getter', description: 'Complete your first goal', icon: '🎯', xp: 150, check: (s) => s.goalsCompleted >= 1 },
  { id: 'goals_5', title: 'Achiever', description: 'Complete 5 goals', icon: '🏅', xp: 400, check: (s) => s.goalsCompleted >= 5 },
  { id: 'journal_1', title: 'Dear Diary', description: 'Write your first journal entry', icon: '📖', xp: 20, check: (s) => s.journalEntries >= 1 },
  { id: 'journal_7', title: 'Thoughtful', description: 'Write 7 journal entries', icon: '✍️', xp: 75, check: (s) => s.journalEntries >= 7 },
  { id: 'journal_30', title: 'Chronicler', description: 'Write 30 journal entries', icon: '📚', xp: 250, check: (s) => s.journalEntries >= 30 },
  { id: 'level_5', title: 'Rising Star', description: 'Reach Level 5', icon: '⭐', xp: 200, check: (s) => s.level >= 5 },
  { id: 'level_10', title: 'Life Champion', description: 'Reach Level 10', icon: '👑', xp: 500, check: (s) => s.level >= 10 },
  { id: 'mood_7', title: 'Self-Aware', description: 'Log mood for 7 days', icon: '🧠', xp: 70, check: (s) => s.moodLogs >= 7 },
  { id: 'health_week', title: 'Health Hero', description: 'Log health data for 7 days', icon: '💚', xp: 100, check: (s) => s.healthLogs >= 7 },
  { id: 'saver', title: 'Smart Saver', description: 'Save money 3 months in a row', icon: '💰', xp: 200, check: (s) => s.savingsMonths >= 3 },
];
